name: Test build main branch

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Extract External Libraries
        run: |
          aws configure set aws_access_key_id ${{ secrets.R2_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.R2_SECRET_ACCESS_KEY }}
          aws configure set default.region auto
          R2_ENDPOINT=${{ secrets.R2_ENDPOINT }}
          URL=$(aws s3 presign s3://external/ExternalLibraries.7z --endpoint-url $R2_ENDPOINT --expires-in 3600)
          curl -o ExternalLibraries.7z  "$URL"
          7z x ExternalLibraries.7z -p${{ secrets.ZIP_PASSWORD }}
        shell: bash

      - name: Create secret props file
        run: |
          echo "<Project>" > Garage61.props
          echo "  <PropertyGroup>" >> Garage61.props
          echo "    <Garage61ClientId>${{ secrets.GARAGE61_CLIENT_ID }}</Garage61ClientId>" >> Garage61.props
          echo "  </PropertyGroup>" >> Garage61.props
          echo "</Project>" >> Garage61.props
      
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2      

      - name: Build the project
        run: msbuild Garage61Data.sln /property:Configuration=Release

      - name: Store artifact
        uses: actions/upload-artifact@v4
        with:
          name: Garage61Data
          path: bin/Release/Garage61Data.*
