name: Test build main branch

on:
  push:
    branches: [ "_main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          lfs: true
          
      - name: Create dist folder
        run:  mkdir dist

      - name: Extract External Libraries
        run: 7z x ExternalLibraries.7z -p${{ secrets.ZIP_PASSWORD }}
        shell: powershell

      - name: Create secret props file
        run: |
          echo "<Project>" > Garage61.props
          echo "  <PropertyGroup>" >> Garage61.props
          echo "    <Garage61ClientId>${{ secrets.GARAGE61_CLIENT_ID }}</Garage61ClientId>" >> Garage61.props
          echo "  </PropertyGroup>" >> Garage61.props
          echo "</Project>" >> Garage61.props
      
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2      

      - name: Build the project
        run: msbuild Garage61Data.sln /property:Configuration=Release
